### ISSUE TITLE
Voluntary demographic reporting

### ISSUE THREAD

**Issue by abacon** [WeAllJS/wheelie-slack-app#2]
When a new user joins, have wheelie ask some simple, optional questions about their demographics:
- gender stuff
- race stuff
- culture stuff (?)

Allow them to change their selections.

Periodically report (?) on message distribution by different groups.

**Comment by zkat** [comment]
I was actually thinking of using identity channels for this, after asking in the community -- that would make the stats anonymous, and not need to be that specific. Basically, wheelie can just collect the # of people in each channel, and make a report from that.

But again, see if people are cool with that. We might come up with some sort of anonymous opt-out system, too.

**Comment by zkat** [comment]
I don't know if I like the idea of collecting and storing demographic information about users directly. I think it's best to find other ways to report this, as I said above, based on channel counts and such. So, I'm closing this one.
