### ISSUE TITLE
Command to list admins

### ISSUE THREAD

**Issue by abacon** [WeAllJS/wheelie-slack-app#3]
> Feature request — add a command to view the list of admins, potentially also with their status (online/snooze/offline)

— [lewis](https://wealljs.slack.com/archives/meta-wheelie-dev/p1470821408000100)

**Comment by zkat** [comment]
(that's @lewiscowper, assuming it's ok to @)

**Comment by karanjthakkar** [comment]
@zkat Anyone working on this? I'd like to do this if its up for grabs :)

**Comment by zkat** [comment]
I think we could/should Worse Is Better this, and just have a `?admins`/`?admin` command.

**Comment by zkat** [comment]
Command got added (as a slackbot response). I think this is good enough and means we don't need to go through the bother of adding more code to maintain 😂
