### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by erichelgeson** [WeAllJS/wheelie-slack-app#4]
There's no license currently for this project, we'd like to know it's ok to use this code with our slack community at https://groovycommunity.com/

**Comment by aredridel** [comment]
https://github.com/WeAllJS/wheelie-slack-app/blob/master/package.json#L11

**Comment by erichelgeson** [comment]
Ahh missed that - Thanks!

**Comment by zkat** [comment]
I've been thinking about it and it's probably a good idea to grab the CC0 copyright release thing as a LICENSE file. Even though it's public domain <3

**Comment by zkat** [comment]
I've added a `COPYING` file which includes the complete text of CC0-1.0, which should be an even more obvious marker of intent about the codebase. So I'm gonna close this now. :)
